# Generated by Django 5.0.1 on 2024-01-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.TextField()),
                ('destination', models.TextField()),
                ('mileage', models.IntegerField()),
            ],
        ),
    ]
